kind = "mobile"
previewPath = "/"
title = "FinanceMonitor UG"
version = "1.0.0"
id = "artifacts/finance-monitor"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25648

[services.development]
run = "pnpm --filter @workspace/finance-monitor run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/finance-monitor", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/finance-monitor", "run", "serve" ]

[services.env]
PORT = "25648"
BASE_PATH = "/"
